/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package limpadorpendrive;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Phillipi
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }
    
    public ArrayList<String> apagados = new ArrayList<>();
    
    void apagaTudo(boolean sub, String end, String ext){    
        File dir = new File(end);
        if(dir.isDirectory()) {  
            String[] filhos = dir.list();
            for(int i = 0; i < filhos.length; i++) {  
                File nome = new File(dir, filhos[i]);  
                if(nome.isFile()){
                    if(nome.getName().toUpperCase().endsWith(ext)){
                        if(nome.length() < 1024000){
                            nome.delete();
                            apagados.add(nome.getAbsolutePath());
                        }else{
                            int c = JOptionPane.showConfirmDialog(null ,"O arquivo "+nome.getName()+" é maior que 1MB e a principio não aparenta ser virus.\n\nCaminho:\n"+nome.getAbsolutePath()+"\n\nVocê Reconhece esse arquivo? Caso não o reconheça clique em sim, ou não para mante-lo.", "Confirmar", JOptionPane.YES_NO_OPTION);  
                            if(c == JOptionPane.YES_OPTION){
                                nome.delete();
                                apagados.add(nome.getAbsolutePath());
                            }
                        }
                    }
                }else if(nome.isDirectory() && sub == true){
                    apagaTudo(sub, nome.getAbsolutePath(), ext);
                }
            }
        }
    }
    
    void espera(int t){
        while(true){
            try {
                Thread.sleep(t);
            } catch (InterruptedException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        unidade = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        lnk = new javax.swing.JCheckBox();
        exe = new javax.swing.JCheckBox();
        vbs = new javax.swing.JCheckBox();
        inf = new javax.swing.JCheckBox();
        bat = new javax.swing.JCheckBox();
        scr = new javax.swing.JCheckBox();
        vbe = new javax.swing.JCheckBox();
        cmd = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        desocultar = new javax.swing.JCheckBox();
        alem = new javax.swing.JCheckBox();
        botao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Limpador de Pendrive 1.0");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Escolha a Unidade:");

        unidade.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        unidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A:\\", "B:\\", "C:\\", "D:\\", "E:\\", "F:\\", "G:\\", "H:\\", "I:\\", "J:\\", "K:\\", "L:\\", "M:\\", "N:\\", "O:\\", "P:\\", "Q:\\", "R:\\", "S:\\", "T:\\", "U:\\", "V:\\", "W:\\", "X:\\", "Y:\\", "Z:\\" }));

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Excluir (Apenas no Diretorio Raiz):"));

            lnk.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            lnk.setSelected(true);
            lnk.setText("Arquivos *.lnk");

            exe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            exe.setSelected(true);
            exe.setText("Arquivos *.exe");

            vbs.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            vbs.setSelected(true);
            vbs.setText("Arquivos *.vbs");

            inf.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            inf.setSelected(true);
            inf.setText("Arquivos *.inf");

            bat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            bat.setSelected(true);
            bat.setText("Arquivos *.bat");

            scr.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            scr.setSelected(true);
            scr.setText("Arquivos *.src ");

            vbe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            vbe.setSelected(true);
            vbe.setText("Arquivos *.vbe");

            cmd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            cmd.setSelected(true);
            cmd.setText("Arquivos *.cmd");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lnk)
                        .addComponent(exe)
                        .addComponent(vbs)
                        .addComponent(inf)
                        .addComponent(bat)
                        .addComponent(scr)
                        .addComponent(vbe)
                        .addComponent(cmd))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lnk)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(exe)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(vbs)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(inf)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(bat)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(scr)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(vbe)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cmd))
            );

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Outras Opções"));

            desocultar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            desocultar.setSelected(true);
            desocultar.setText("Desocultar Pastas e Arquivos");

            alem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            alem.setText("Excluir Além do Diretório Raiz");
            alem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    alemActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desocultar)
                        .addComponent(alem))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desocultar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(alem))
            );

            botao.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            botao.setText("Executar Limpeza");
            botao.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botaoActionPerformed(evt);
                }
            });

            jLabel2.setForeground(new java.awt.Color(0, 153, 153));
            jLabel2.setText("Criado Por: Phillipi O. Giobini");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(62, 62, 62))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botao)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        String end = (String) unidade.getSelectedItem();
        apagados.clear();
        String relatorio = "***** Relatório *****\n";
        
        File dir = new File(end);
        if(!dir.isDirectory()){
            JOptionPane.showMessageDialog(null, end+" não é uma unidade valida ou ativa, por favor selecione outra.");
            return;
        }
        
        botao.setText("Aguarde...");
        botao.setEnabled(false);
        JOptionPane.showMessageDialog(null, "AVISO:\n\nEvite fazer outras tarefas no seu computador enquanto a limpeza estiver em andamento.\n\nClique em OK para começar.");
    
        if(desocultar.isSelected()){
            relatorio += "\nPastas desocultadas com sucesso.\n";
            try {
                Runtime.getRuntime().exec("cmd /c attrib "+end+"*.* /d /s +a -h -r -s");
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }
            espera(8000);
        }
        
        if(lnk.isSelected()){
            apagaTudo(alem.isSelected(), end, ".LNK");
        }
        
        if(exe.isSelected()){
            apagaTudo(alem.isSelected(), end, ".EXE");
        }
        
        if(vbs.isSelected()){
            apagaTudo(alem.isSelected(), end, ".VBS");
        }
        
        if(inf.isSelected()){
            apagaTudo(alem.isSelected(), end, ".INF");
        }
        
        if(bat.isSelected()){
            apagaTudo(alem.isSelected(), end, ".BAT");
        }
        
        if(scr.isSelected()){
            apagaTudo(alem.isSelected(), end, ".SCR");
        }
        
        if(vbe.isSelected()){
            apagaTudo(alem.isSelected(), end, ".VBE");
        }
        
        if(cmd.isSelected()){
            apagaTudo(alem.isSelected(), end, ".CMD");
        }
        
        relatorio +="\nArquivos apagados:\n\n";
        for(int i=0; i < apagados.size(); i++){
            relatorio += apagados.get(i)+"\n";
        }
        
        botao.setText("Executar Limpeza");
        botao.setEnabled(true);
        
        int i = JOptionPane.showConfirmDialog(null ,"Limpeza completa. Deseja exibir o relatorio?", "Confirmar",JOptionPane.YES_NO_OPTION);  
        if(i == JOptionPane.YES_OPTION){  
            Relatorio r = new Relatorio();
            r.setLocationRelativeTo(null);
            r.setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE );
            r.muda(relatorio);
            r.setVisible(true);
        }
    }//GEN-LAST:event_botaoActionPerformed

    private void alemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alemActionPerformed
        if(alem.isSelected()){
            JOptionPane.showMessageDialog(null, "ATENÇÃO:\n\nTome muito cuidado ao usar essa opção pois ela apagará alem do diretório raiz.\n\nCertifique que as extensões estejam selecionadas corretamente.");
        }
    }//GEN-LAST:event_alemActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alem;
    private javax.swing.JCheckBox bat;
    private javax.swing.JButton botao;
    private javax.swing.JCheckBox cmd;
    private javax.swing.JCheckBox desocultar;
    private javax.swing.JCheckBox exe;
    private javax.swing.JCheckBox inf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox lnk;
    private javax.swing.JCheckBox scr;
    private javax.swing.JComboBox unidade;
    private javax.swing.JCheckBox vbe;
    private javax.swing.JCheckBox vbs;
    // End of variables declaration//GEN-END:variables
}
